// apps/web/src/app/shared/sync-status.component.ts
import { Component, inject, signal } from '@angular/core';
import { ApiClientService } from '../core/services/api-client.service';
import { BadgeComponent } from '../ui/badge.component';

@Component({
  selector: 'app-sync-status',
  standalone: true,
  imports: [BadgeComponent],
  template: `
    @if (online() && api.pendingCount() === 0) {
      <app-badge
        variant="outline"
        class="gap-1.5 text-emerald-700 dark:text-emerald-400 border-emerald-200 dark:border-emerald-900 bg-emerald-50 dark:bg-emerald-950/40"
      >
        <span class="w-1.5 h-1.5 rounded-full bg-emerald-500"></span>
        Synced
      </app-badge>
    } @else {
      <button (click)="retry()" title="Click to retry syncing now" type="button">
        <app-badge
          variant="outline"
          class="gap-1.5 text-amber-800 dark:text-amber-400 border-amber-200 dark:border-amber-900 bg-amber-50 dark:bg-amber-950/40 cursor-pointer"
        >
          <span class="w-1.5 h-1.5 rounded-full bg-amber-500"></span>
          {{ online() ? 'Online' : 'Offline' }}
          {{ api.pendingCount() > 0 ? ' · ' + api.pendingCount() + ' pending' : '' }}
        </app-badge>
      </button>
    }
  `,
})
export class SyncStatusComponent {
  api = inject(ApiClientService);
  online = signal(typeof navigator !== 'undefined' ? navigator.onLine : true);

  constructor() {
    if (typeof window === 'undefined') return;
    window.addEventListener('online', () => this.online.set(true));
    window.addEventListener('offline', () => this.online.set(false));
    this.api.getPendingCount().then((n) => this.api.pendingCount.set(n));
  }

  retry() {
    void this.api.flushQueue();
  }
}

// src/components/SyncStatus.tsx
"use client";

import { useEffect, useState } from "react";
import { startAutoSync, syncEvents, getPendingCount, flushQueue } from "@/lib/api-client";
import { Badge } from "@/components/ui/badge";

export default function SyncStatus() {
  // Start "online" on both server and client's first render so hydration
  // matches; the real value (which only the browser knows) lands right
  // after mount via the effect below.
  const [online, setOnline] = useState(true);
  const [pending, setPending] = useState(0);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- syncing to browser-only navigator.onLine post-mount
    setOnline(navigator.onLine);
    const onOnline = () => setOnline(true);
    const onOffline = () => setOnline(false);
    window.addEventListener("online", onOnline);
    window.addEventListener("offline", onOffline);

    const onPendingChange = (e: Event) => setPending((e as CustomEvent<number>).detail);
    syncEvents.addEventListener("pending-change", onPendingChange);

    getPendingCount().then(setPending);
    const stop = startAutoSync();

    return () => {
      window.removeEventListener("online", onOnline);
      window.removeEventListener("offline", onOffline);
      syncEvents.removeEventListener("pending-change", onPendingChange);
      stop?.();
    };
  }, []);

  if (online && pending === 0) {
    return (
      <Badge variant="outline" className="gap-1.5 text-emerald-700 dark:text-emerald-400 border-emerald-200 dark:border-emerald-900 bg-emerald-50 dark:bg-emerald-950/40">
        <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
        Synced
      </Badge>
    );
  }

  return (
    <button
      onClick={() => void flushQueue().then((r) => setPending(r.remaining))}
      title="Click to retry syncing now"
    >
      <Badge variant="outline" className="gap-1.5 text-amber-800 dark:text-amber-400 border-amber-200 dark:border-amber-900 bg-amber-50 dark:bg-amber-950/40 cursor-pointer">
        <span className="w-1.5 h-1.5 rounded-full bg-amber-500" />
        {online ? "Online" : "Offline"}
        {pending > 0 ? ` · ${pending} pending` : ""}
      </Badge>
    </button>
  );
}
